### ISSUE TITLE
jasmine-rails is not detecting any specs

### ISSUE THREAD

**Issue by kratos6753** [searls/jasmine-rails#152]
Rails version : 4.1.8
Ruby version : 2.1.2
Jasmine-rails version : 0.10.5
Jasmine-rails is not detecting any of the javascript specs in my project. But it works for other dummy app with same versions and same jasmine.yml configuration. What could be the reason?

**Comment by JackWCollins** [comment]
@kratos6753 Did you ever find a solution to this? I'm running into this problem now.
