### ISSUE TITLE
Getting routing error on trying to launch simple test

### ISSUE THREAD

**Issue by pduvvuri** [searls/jasmine-rails#157]
Trying to setup and launch spec tests and getting routing error
 
on chrome : http://localhost:3000/specs
bundle exec rails s
INFO dev: Started GET "/specs" for ::1 
FATAL dev: 
ActionController::RoutingError (No route matches [GET] "/specs"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'

gems installed phantomjs-1.9.8.0.gem
jasmine-core-2.1.3.gem
jasmine-rails-0.10.6.gem
rails version 4.2.0

RAILS_ENV=test bundle exec rake spec:javascript
rake aborted!
NoMethodError: undefined method `use_phantom_gem?' for JasmineRails:Module

spec folder already has some ruby spec files.Added a simple foo_spec coffee file to javascripts folder. Folled the initial instructions of adding jasmine.yml and change to routes file

**Comment by searls** [comment]
I don't think this is something others can help you debug based on that description. Could you please post a sample application?

**Comment by pduvvuri** [comment]
Will debug on my side and get back. Thanks
