### ISSUE TITLE
jasmine-rails stuck in a loop

### ISSUE THREAD

**Issue by c0mrade** [searls/jasmine-rails#161]
For some reason when I run :
localhost:3000/specs

My tests run in a loop, they all pass but still in a loop. I got 353 specs, as soon as they're done they start running from the beginning.

Anyone else experiencing this behavior?

**Comment by searls** [comment]
This is typically caused by a spec or app code that's doing something to refresh the page. Recommend you manually bisect your test suite to identify what's causing it.

**Comment by c0mrade** [comment]
Thanks, will do
