### ISSUE TITLE
Tests are run twice in console when using spring

### ISSUE THREAD

**Issue by joker-777** [searls/jasmine-rails#165]
The tests are run twice if you use spring. My command looks like this `spring rake spec:javascript`. Using `bundle exec rake spec:javascript` works though.
The same weird behavior also happens when I add `RAILS_ENV=test'`. For example `RAILS_ENV=test bundle exec rake spec:javascript`.

**Comment by searls** [comment]
try disabling spring and see what happens

**Comment by joker-777** [comment]
Strange thing happend. After I removed the gem `spring-commands-rspec` it coplained that it couldn't load `.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/specifications/default/bin/rake` when I wanted to run any `rake` command. Reinstalling rake fixed this and it also fixed this problem here too. I can't reproduce this error anymore, with or without `spring-commands-rspec`.
Thanks for you quick response. I was really impressed.
