### ISSUE TITLE
Unable to find fixtures

### ISSUE THREAD

**Issue by workmaster2n** [searls/jasmine-rails#169]
I have `jasmine-jquery.js` under my `app/assets/javascripts` folder (for inclusion via asset pipeline).

I have `spec/javascripts/fixtures/index.html` defined as follows:

    <div id="container"></div>

My spec is as follows

    #= require jquery
    #= require jasmine-jquery

    describe 'deployment page', ->
      it 'works', ->
        loadFixtures('index.html')

I am getting this error:

     Fixture could not be loaded: spec/javascripts/fixtures/index.html (status: error, 

I have this same setup with the `jasmine` gem (except I include the files via  `jasmine.yml`) and this spec operates with no errors. 

I think I've got something configured incorrectly. Is there something different I need to do since the rails server is now serving the assets (since we are visiting `localhost:3000`)?

Thanks

**Comment by searls** [comment]
Jasmine-rails doesn't support external fixture files by design. Consider
using jasmine-fixture instead.

**Comment by workmaster2n** [comment]
Is there a way to load up the rails views for a spec since we are serving the specs from localhost?

**Comment by searls** [comment]
That is also not desired behavior, sorry. I wrote about it more here:
http://searls.testdouble.com/posts/2011-12-11-jasmine-fixtures.html
