### ISSUE TITLE
Phantomjs 2.1.1 segfaults with jasmine-rails

### ISSUE THREAD

**Issue by shamus** [searls/jasmine-rails#184]
I tried to set up a new rails project today with jasmine-rails and phantomjs 2.1.1 and found that phantomjs segfaults with the out of the box set up.  It appears that `lib/assets/javascripts/jasmine-runner.js` registers a `page.onInitialized` callback that is being executed multiple times which I believe results in multiple calls to phantom.exit.

I don't really know why that would be happening.  I've submitted #183 which alleviates the problem but it feels more like treating a symptom rather than the root problem.

**Comment by searls** [comment]
Landed in 0.12.3
