### ISSUE TITLE
"phantom_options: --debug=true" fails with "Invalid values for 'debug' option."

### ISSUE THREAD

**Issue by simook** [searls/jasmine-rails#192]
jasmine-rails 0.11.0
phantomjs 1.9.8

Steps to reproduce:
1. Add the following to `jasmine.yml`
    `phantom_options: --debug=true`
2. Run the jasmine rake task from the command line, `rake spec:javascript`
3. The rake task will error out with "Invalid values for 'debug' option."
4. Verify the debug option is valid by running `phantomjs --debug=true`

Expected Results:
To run phantomjs with the debug option enabled.

**Comment by searls** [comment]
Interesting. Did you try debugging the code to see what that YAML parsed as and what got passed to the phantomjs shell-out?

**Comment by searls** [comment]
Closed due to inactivity

**Comment by bolshakov** [comment]
Error happens if you configure jasmine-rails to pass to phantom several options. For example:

```yml
phantom_options: --debug=true --web-security=false
```

It will be translated into `system("phantom", "--debug=true --web-security=false")`, but should be `system("phantom", "--debug=true",  "--web-security=false")`:

```ruby 
> system("/Users/tema/.phantomjs/2.1.1/darwin/bin/phantomjs", "--debug=true --web-security=false")
Invalid values for 'debug' option.
=> true
```
