### ISSUE TITLE
How to make jasmine-rails find jasmine

### ISSUE THREAD

**Issue by snoblenet** [searls/jasmine-rails#193]
`jasmine-rails` is installed, as per `Gemfile.lock`:

````
    jasmine-core (2.4.1)
    jasmine-rails (0.12.4)
      jasmine-core (>= 1.3, < 3.0)
      phantomjs (>= 1.9)
      railties (>= 3.2.0)
      sprockets-rails
````

Though i don't actually want the PhantomJS gem as I'm using PhantomJS installed via `apt-get`:

````
$phantomjs -v
1.9.0
$ which phantomjs
/usr/bin/phantomjs
````

````
# spec/javascripts/support/jasmine.yml
use_phantom_gem: false
````

Our app's asset pipeline has been highly customised in ways I can't control, so to ensure `jasmine-rails` can find `jasmine.js` etc, I added the following files:

````
-- spec
  -- javascripts
      -- vendor
        -- jasmine
          -- 2.4.1
            -- jasmine.js
            -- boot.js
            -- jasmine-html.js
            -- jasmine.css
````
     
I've told `jasmine-rails` to look for them:

````
# spec/javascripts/support/jasmine.yml
include_dir:
  - spec/javascripts/support/vendor
````

And yet it seems that `jasmine-rails` can't find the files:

````
$ bundle exec rake spec:javascript
Running `"phantomjs" "" "/turbo/vendor/bundle/ruby/2.3.0/gems/jasmine-rails-0.12.4/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///turbo/tmp/jasmine/runner.html?spec="`
Running: file:///turbo/tmp/jasmine/runner.html?spec=
ERROR: ReferenceError: Can't find variable: jasmine
TRACE:
 -> file:///turbo/tmp/jasmine/assets/jasmine-console-reporter.js: 15
 -> file:///turbo/tmp/jasmine/assets/jasmine-console-reporter.js: 131
rake aborted!
Error executing command: "phantomjs" "" "/turbo/vendor/bundle/ruby/2.3.0/gems/jasmine-rails-0.12.4/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///turbo/tmp/jasmine/runner.html?spec="
````

The weird thing is, I've taken a look at the contents of `/tmp/jasmine` and at first glance it looks like it should all work, even without my extra fiddling, as the file at `/tmp/jasmine/runner.html` reads...

````

<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html;charset=UTF-8" http-equiv="Content-Type"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Jasmine Specs</title>

    <link rel="stylesheet" media="screen" href="./assets/jasmine.css" />
<link rel="stylesheet" media="screen" href="./assets/jasmine-specs.css" />
    <script src="./assets/jasmine.js" defer="defer"></script>
<script src="./assets/jasmine-html.js" defer="defer"></script>
<script src="./assets/json2.js" defer="defer"></script>
<script src="./assets/boot.js" defer="defer"></script>
<script src="./assets/jasmine-console-shims.js" defer="defer"></script>
<script src="./assets/jasmine-console-reporter.js" defer="defer"></script>
<script src="./assets/jasmine-specs.js" defer="defer"></script>
  </head>
  <body data-no-turbolink>
    <div id="jasmine_content"></div>
  </body>
</html>
````

...and all the files it's looking for are in `tmp/jasmine/assets`.

**But here is the weird important thing I've just discovered while writing everything that's above,** the following files are present but completely empty:

- `tmp/jasmine/assets/jasmine.js`
- `tmp/jasmine/assets/jasmine.css`
- `tmp/jasmine/assets/boot.js`
- `tmp/jasmine/assets/jasmine-html.js`
- `tmp/jasmine/assets/json2.js` 

Meanwhile, these files are present and fully formed:

- `tmp/jasmine/assets/jasmine-console-reporter.js`
- `tmp/jasmine/assets/jasmine-console-shims.js`
- `tmp/jasmine/assets/jasmine-specs.js`

At this stage, I'm thinking about forking `jasmine-rails` to create a version that just includes `jasmine.js` etc in the `<head>`, but that's obviously not maintainable.

I've tried removing all the customisations (`/spec/javascripts/vendor` etc) but I face the same problem.

What should I do? Thanks.

**Comment by searls** [comment]
I really struggled to figure out what even was happening in your case, so when I read "Our app's asset pipeline has been highly customised in ways I can't control", I can't help but assume this is going to require some one-off hack that you'll end up being stuck with and doesn't belong in the gem prior.

Could you please post a minimum example project that replicates the problem? It's as (if not more) likely to be an issue with your app's relationship to sprockets than to jasmine-rails.

Will close until then.
