### ISSUE TITLE
Using angular 1.3.2 will break jasmine specs

### ISSUE THREAD

**Issue by lucasklaassen** [searls/jasmine-rails#206]
Received the following error when using angular 1.6.2 and jasmine-rails version 0.14.1
```
ERROR: TypeError: 'undefined' is not a function (evaluating 'angular.module('ngResource', ['ng']).
  info({ angularVersion: '1.6.3' })')
-> jasmine-specs.js: 71272
-> jasmine-specs.js: 71685
```
Updating to angular 1.6.3 fixes this issue.

**Comment by searls** [comment]
Hello -- I really have no idea what's going on here, and jasmine-rails doesn't have a dependency on Angular, so I'm going to thank you for the FYI and close this unless there's some action I need to take.
