### ISSUE TITLE
Add support for jasmine-core 3.x.x?

### ISSUE THREAD

**Issue by mileslane** [searls/jasmine-rails#236]
Will this project be able to work with the more recent releases of jasmine-core soon?

**Comment by searls** [comment]
This project is not under active development, but I still am happy to look at PRs from folks so long as they can keep the builds green

**Comment by stephaniefiddy** [comment]
Is this still being worked on? I noticed the pull request for this is still open. 
I'm currently blocked on upgrading jasmine to 3.0.0 until jasmine-rails can support the newer version of jasmine-core.

**Comment by searls** [comment]
Thanks for the reminder, I fixed the build and released on 0.15.0
