### ISSUE TITLE
rake spec:javascript ran in the wrong rails environment

### ISSUE THREAD

**Issue by RobertAudi** [searls/jasmine-rails#53]
This might be a special case but it's a issue nonetheless. The `rake spec:javascript` command runs the specs in the wrong environment; that is, not in the test environment. I am using SSL in my app, which I've disabled in the test environment and I redirect all non-HTTPS traffic to their HTTPS equivalent (again, disabled in the test environment). When I ran `rake spec:javascript` I got the following error:

~~~sh
Jasmine runner at '/specs' returned a 301 error: Moved Permanently
~~~

This error is logical in my case, but I think that the rake task should run in the test environment anyway.

I managed to avoid the error using the following command:

~~~sh
RAILS_ENV=test rake spec:javascript
~~~

**Comment by searls** [comment]
This is fixed in https://github.com/searls/jasmine-rails/releases/tag/v0.12.0 by #173
