### ISSUE TITLE
Failing test results in an error message from phantomjs

### ISSUE THREAD

**Issue by jondkinney** [searls/jasmine-rails#66]
If all my specs pass then I don't get an error. If I have a failure then I get this error. Any thoughts? Only thing I could think of is perhaps on line 28 of the jasmine-rails_tasks.rake file phantomjs is upset about the missing spec_filter?

Rails 3.2.14
Ruby 2.0.0-p247
OS X 10.8.4 
PhantomJS 1.9.0.

Thanks!
Jon

```shell
± RAILS_ENV=test bundle exec rake spec:javascript                 ruby-2.0.0-p247@bolstr
$ phantomjs "/Users/jon/.rvm/gems/ruby-2.0.0-p247@bolstr/gems/jasmine-rails-0.4.5/lib/tasks/runner.js" "file:///Users/jon/Sites/rails/bolstr/bolstr/spec/tmp/runner.html?spec="
Running: file:///Users/jon/Sites/rails/bolstr/bolstr/spec/tmp/runner.html?spec=
Starting...
Foo : does something else
  Expected 5 to be 3.

Finished
-----------------
2 specs, 1 failure in 0.005s.

ConsoleReporter finished
rake aborted!
Error executing command: phantomjs "/Users/jon/.rvm/gems/ruby-2.0.0-p247@bolstr/gems/jasmine-rails-0.4.5/lib/tasks/runner.js" "file:///Users/jon/Sites/rails/bolstr/bolstr/spec/tmp/runner.html?spec="
/Users/jon/.rvm/gems/ruby-2.0.0-p247@bolstr/gems/jasmine-rails-0.4.5/lib/tasks/jasmine-rails_tasks.rake:5:in `run_cmd'
/Users/jon/.rvm/gems/ruby-2.0.0-p247@bolstr/gems/jasmine-rails-0.4.5/lib/tasks/jasmine-rails_tasks.rake:28:in `block (2 levels) in <top (required)>'
/Users/jon/.rvm/gems/ruby-2.0.0-p247@bolstr/bin/ruby_noexec_wrapper:14:in `eval'
/Users/jon/.rvm/gems/ruby-2.0.0-p247@bolstr/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => spec:javascript
(See full trace by running task with --trace)
```

**Comment by searls** [comment]
Closing unless someone's still bugged by this

**Comment by juandazapata** [comment]
I've hit this very same problem with a small difference. My tests in the browser are green, in the console are green as well, but the command exits soon after the tests are green.

```
ruby 2.2.2
jasmine 0.12.4
rails 4
```

![jasmine_specs](https://cloud.githubusercontent.com/assets/145506/16509826/697d060e-3f06-11e6-8e8b-eebf118be7c7.png)

![terminal](https://cloud.githubusercontent.com/assets/145506/16509817/534e19b8-3f06-11e6-876c-59dbfcb5fbbf.png)

**Comment by juandazapata** [comment]
Ended up by removing `jasmine-rails` and going with vanilla `jasmine` gem.
